version = 0.1
[default.deploy.parameters]
stack_name = "sam-crypto-guessr"
resolve_s3 = true
s3_prefix = "sam-crypto-guessr"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
